### ISSUE TITLE
Add ARM support for Java Maven packages

### ISSUE THREAD

**Issue by jwrosewell** [51Degrees/device-detection-java#12]
The underlying C/C++ code supports ARM processors. Amend the Maven package to include compiled binaries for popular CPU/OS combinations.

**Comment by jorabin-51d** [comment]
ARM / Linux is available - we will add Apple M1 support.

**Comment by tungntpham** [comment]
ARM binaries for Apple M1 is now included in the package [here](https://search.maven.org/artifact/com.51degrees/device-detection.hash.engine.on-premise/4.3.13/jar)
