### ISSUE TITLE
Memory leak with version 4.3.16

### ISSUE THREAD

**Issue by jonathanbl** [51Degrees/device-detection-java#15]
Hi 51degrees team, 

This is Jonathan @ Everflow. 

We released a new version of our solution yesterday and as part of this release was a bump from the Java library 4.1.9 to 4.3.16. The release initially went fine but we quickly identified a memory leak with the 4.3.16 version. As you can see in the screenshot below, it is pretty obvious how 4.3.16 had a pretty significant impact on the memory consumption. 
We used jmap to perform a heap dump but we were not able to identify anything useful that would help tracking the leak. Please let me know if you would like to have access to the hprof file (or anything else to help with debugging). 
At this point we rolled back to the previous working version but we would like to move again to the latest version considering it supports the M1 chip + UACH support. 
What do you think would be the best move here, should we try upgrading to 4.4.2? Thank you for your help and let us know if we can do anything to help identify the issue. 

**OS**
Debian GNU/Linux 11 (bullseye) and 

**Java**
openjdk version "1.8.0_322"
OpenJDK Runtime Environment (build 1.8.0_322-b06)
OpenJDK 64-Bit Server VM (build 25.322-b06, mixed mode)

<img width="1292" alt="Screen Shot 2022-04-24 at 8 37 14 PM" src="https://user-images.githubusercontent.com/1969907/165003751-64379b16-2677-4242-b3f4-9a38ec757714.png">

**Comment by tungntpham** [comment]
Hi @jonathanbl,

Many thanks for raising this issue with us. In 4.3 or above version, there was a change in the usage of our V4 interface. That means there is expected to be one creation of a pipeline and then explicit closure of each flowdata created from the pipeline in the following model:

```
// explicitly dispose pipeline when done
try (Pipeline pipeline = new DeviceDetectionPipelineBuilder()
        .useOnPremise(detectionFile, false)
        /* some pipeline configuration */
        .build()) {
    /* some preparatory stuff ... */
    // explicitly dispose the flowdata when it is finished by using try with resources
    try (FlowData data = pipeline.createFlowData()) {
        /* add some evidence */
        data.addEvidence("some evidence", new byte[1024]);
        data.process();
        /* do stuff with the results of the detection */
    }
}
```

In the screenshot that you have provided, we can see that the memory is being freed correctly and no memory leak has occurred, so this seems to only be a memory consumption issue. Thus, I hope, by updating the usage to the above model, the memory consumption will be much better.

I will close this for now, but please feel free to reopen it if you think there is a memory leak issue. If that is the case, please provide us with additional details on the garbage collection settings being used.

Many thanks,
Tung.

**Comment by jonathanbl** [comment]
Hi @tungntpham - thank you for the reply

Just want to make sure I understand your suggestion for 4.3+. As you can see in the code below, we are using your device detection library in the context of a singleton. Only when we initiate the singleton that we create a new DeviceDetectionPipelineBuilder. 
Are you suggesting we move the DeviceDetectionPipelineBuilder into the detect function and open / close the pipeline for every requests?

```
public class FiftyOneDegrees {

    private final Pipeline pipeline;

    private static class Holder {
        private static final FiftyOneDegrees instance = new FiftyOneDegrees();
    }

    public static FiftyOneDegrees getInstance() {
        return Holder.instance;
    }

    private FiftyOneDegrees() {
        try {
            pipeline = new DeviceDetectionPipelineBuilder()
                    .useOnPremise(Configurations.getFiftyOneDegreesFilePath(), false)
                    .setPerformanceProfile(Constants.PerformanceProfiles.LowMemory)
                    .setShareUsage(LocalConfiguration.CONFIG.getIsShareFiftyOneDegreesUsage())
                    .setProperty("PlatformName")
                    .setProperty("PlatformVersion")
                    .setProperty("IsMobile")
                    .setProperty("IsTablet")
                    .setProperty("DeviceType")
                    .setProperty("BrowserName")
                    .setProperty("BrowserVersion")
                    .setProperty("HardwareVendor")
                    .setProperty("HardwareModel")
                    .setProperty("HardwareName")
                    .setProperty("IsCrawler")
                    .setUsePredictiveGraph(true
                    .setUsePerformanceGraph(true)
                    .build();

            Date dataPublishedDateTime = pipeline.getElement(OnPremiseAspectEngine.class).getDataFileMetaData().getDataPublishedDateTime();
            DEVICE_DETECTION_VERSION.set(1, new SimpleDateFormat("yyyy-MM-dd").format(dataPublishedDateTime));
        }
        catch (Exception ex) {
            throw new RuntimeException(ex);
        }
    }

    public DeviceInformationEntity detect(String userAgent, String acceptLanguage) {
        FlowData flowData = pipeline.createFlowData();
        flowData
                .addEvidence("header.user-agent", userAgent)
                .addEvidence("header.usage-from", "everflow")
                .process();

        DeviceDataHash device = flowData.get(DeviceDataHash.class);

        DeviceInformationEntity deviceInformationEntity = new DeviceInformationEntity();

        ...

        return deviceInformationEntity;
    }

   ...
}
```

**Comment by tungntpham** [comment]
Hi @jonathanbl,

No, the pipeline can be created as a singleton as you are using and that is what we recommend. Just make sure to close the pipeline once is no longer required.

In term of the flowData, its creation and close should be done using the 'try with resource' pattern to make sure any native resource held in the flowData is freed immediately after a detection, reducing the memory consumption.

Hope that answered your question.

Kind regards,
Tung.

**Comment by jonathanbl** [comment]
Worked well, thank you @tungntpham

**Comment by lh15** [comment]
@tungntpham I'm trying to understand this line. "Just make sure to close the pipeline once is no longer required."

I have a singleton but it is used by request threads. I can close it on server shutdown perhaps, but not before.

(I can put the flowdata code in a try-with-resources)

Thanks

**Comment by jwrosewell** [comment]
The example shows how the pipeline is created and then closes using try-with-resources. See this [line](https://github.com/51Degrees/device-detection-java/blob/c1c195a16f2ad5ef94f14ab823de5511e306f2cc/device-detection.examples/console/src/main/java/fiftyone/devicedetection/examples/console/GettingStartedOnPrem.java#L109).

If this is not possible then you are responsible for calling close() on the Pipeline instance. If you have the pipeline as a singleton then you'd indeed close it during shutdown. See the [close](https://github.com/51Degrees/pipeline-java/blob/93994b6bec7a1f71da36a84c86c1775532e82e10/pipeline.core/src/main/java/fiftyone/pipeline/core/flowelements/PipelineDefault.java#L368) method of the implementation or the AutoCloseable interface.

For others reading this the flowdata must be in a try-with-resources block. See this [line](https://github.com/51Degrees/device-detection-java/blob/c1c195a16f2ad5ef94f14ab823de5511e306f2cc/device-detection.examples/console/src/main/java/fiftyone/devicedetection/examples/console/GettingStartedOnPrem.java#L146).
