### ISSUE TITLE
Issues running device detection in Google Cloud Dataflow

### ISSUE THREAD

**Issue by samuel-flix** [51Degrees/device-detection-java#17]
We are trying to migrate from version 3 to 4. Currently, we are using device-detection-core:3.2.18.1 and we are creating the Provider as below

```
        String fiftyoneDataFile = resourceToFile("/51Degrees.dat", "51Degrees.dat");
        LOG.info("Loaded data file");
        try {
            return new fiftyone.mobile.detection.Provider(MemoryFactory.create(fiftyoneDataFile));
        } catch (IOException e) {
            throw new FMException(e);
        }
```

Now we are trying to migrate to version device-detection:4.4.18. Below is how we are creating the pipeline
```
        String dataFileLocation = resourceToFile("/Enterprise-HashV41.hash", "Enterprise-HashV41.hash");
        System.setProperty("DataFile", dataFileLocation);
        File optionsFile = new File(resourceToFile("/51DegreesPipeline.xml", "51DegreesPipeline.xml"));
        PipelineOptions pipelineOptions = PipelineOptionsFactory.getOptionsFromFile(optionsFile);
        Pipeline pipeline = new FiftyOnePipelineBuilder()
                .buildFromConfiguration(pipelineOptions);
```

In our local environment, we are able to fetch the device details. But when we run it in the Google Cloud Dataflow, we are getting the below exception. 

`Error message from worker: fiftyone.pipeline.core.exceptions.PipelineConfigurationException: Failed to create builder 'fiftyone.devicedetection.hash.engine.onpremise.flowelements.DeviceDetectionHashEngineBuilder'. See inner, 'cause' exception for more details fiftyone.pipeline.core.flowelements.PipelineBuilder.getBuilder(PipelineBuilder.java:530) fiftyone.pipeline.core.flowelements.PipelineBuilder.addElementToList(PipelineBuilder.java:215) fiftyone.pipeline.core.flowelements.PipelineBuilder.buildFromConfiguration(PipelineBuilder.java:107) eu.flixmedia.dataflow.refresh.device.details.dofn.LocalDeviceInfoService.initializePipeline(LocalDeviceInfoService.java:104) eu.flixmedia.dataflow.refresh.device.details.dofn.LocalDeviceInfoService.getDeviceInfo(LocalDeviceInfoService.java:111) eu.flixmedia.dataflow.refresh.device.details.dofn.LocalDeviceInfoService.addDeviceInfoDetails(LocalDeviceInfoService.java:68) eu.flixmedia.dataflow.refresh.device.details.dofn.LocalDeviceInfoService.processElement(LocalDeviceInfoService.java:53) Caused by: java.lang.reflect.InvocationTargetException java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490) fiftyone.pipeline.core.flowelements.PipelineBuilder.getBuilder(PipelineBuilder.java:524) fiftyone.pipeline.core.flowelements.PipelineBuilder.addElementToList(PipelineBuilder.java:215) fiftyone.pipeline.core.flowelements.PipelineBuilder.buildFromConfiguration(PipelineBuilder.java:107) eu.flixmedia.dataflow.refresh.device.details.dofn.LocalDeviceInfoService.initializePipeline(LocalDeviceInfoService.java:104) eu.flixmedia.dataflow.refresh.device.details.dofn.LocalDeviceInfoService.getDeviceInfo(LocalDeviceInfoService.java:111) eu.flixmedia.dataflow.refresh.device.details.dofn.LocalDeviceInfoService.addDeviceInfoDetails(LocalDeviceInfoService.java:68) eu.flixmedia.dataflow.refresh.device.details.dofn.LocalDeviceInfoService.processElement(LocalDeviceInfoService.java:53) eu.flixmedia.dataflow.refresh.device.details.dofn.LocalDeviceInfoService$DoFnInvoker.invokeProcessElement(Unknown Source) org.apache.beam.runners.dataflow.worker.repackaged.org.apache.beam.runners.core.SimpleDoFnRunner.invokeProcessElement(SimpleDoFnRunner.java:222) org.apache.beam.runners.dataflow.worker.repackaged.org.apache.beam.runners.core.SimpleDoFnRunner.processElement(SimpleDoFnRunner.java:183) org.apache.beam.runners.dataflow.worker.SimpleParDoFn.processElement(SimpleParDoFn.java:335) org.apache.beam.runners.dataflow.worker.util.common.worker.ParDoOperation.process(ParDoOperation.java:44) org.apache.beam.runners.dataflow.worker.util.common.worker.OutputReceiver.process(OutputReceiver.java:49) org.apache.beam.runners.dataflow.worker.SimpleParDoFn$1.output(SimpleParDoFn.java:280) org.apache.beam.runners.dataflow.worker.repackaged.org.apache.beam.runners.core.SimpleDoFnRunner.outputWindowedValue(SimpleDoFnRunner.java:256) org.apache.beam.runners.dataflow.worker.repackaged.org.apache.beam.runners.core.SimpleDoFnRunner.access$700(SimpleDoFnRunner.java:74) org.apache.beam.runners.dataflow.worker.repackaged.org.apache.beam.runners.core.SimpleDoFnRunner$DoFnProcessContext.output(SimpleDoFnRunner.java:580) org.apache.beam.runners.dataflow.worker.repackaged.org.apache.beam.runners.core.SimpleDoFnRunner$DoFnProcessContext.output(SimpleDoFnRunner.java:568) org.apache.beam.sdk.io.gcp.bigquery.PassThroughThenCleanup$IdentityFn.processElement(PassThroughThenCleanup.java:83) org.apache.beam.sdk.io.gcp.bigquery.PassThroughThenCleanup$IdentityFn$DoFnInvoker.invokeProcessElement(Unknown Source) org.apache.beam.runners.dataflow.worker.repackaged.org.apache.beam.runners.core.SimpleDoFnRunner.invokeProcessElement(SimpleDoFnRunner.java:222) org.apache.beam.runners.dataflow.worker.repackaged.org.apache.beam.runners.core.SimpleDoFnRunner.processElement(SimpleDoFnRunner.java:183) org.apache.beam.runners.dataflow.worker.SimpleParDoFn.processElement(SimpleParDoFn.java:335) org.apache.beam.runners.dataflow.worker.util.common.worker.ParDoOperation.process(ParDoOperation.java:44) org.apache.beam.runners.dataflow.worker.util.common.worker.OutputReceiver.process(OutputReceiver.java:49) org.apache.beam.runners.dataflow.worker.util.common.worker.ReadOperation.runReadLoop(ReadOperation.java:201) org.apache.beam.runners.dataflow.worker.util.common.worker.ReadOperation.start(ReadOperation.java:159) org.apache.beam.runners.dataflow.worker.util.common.worker.MapTaskExecutor.execute(MapTaskExecutor.java:77) org.apache.beam.runners.dataflow.worker.BatchDataflowWorker.executeWork(BatchDataflowWorker.java:411) org.apache.beam.runners.dataflow.worker.BatchDataflowWorker.doWork(BatchDataflowWorker.java:380) org.apache.beam.runners.dataflow.worker.BatchDataflowWorker.getAndPerformWork(BatchDataflowWorker.java:305) org.apache.beam.runners.dataflow.worker.DataflowBatchWorkerHarness$WorkerThread.doWork(DataflowBatchWorkerHarness.java:140) org.apache.beam.runners.dataflow.worker.DataflowBatchWorkerHarness$WorkerThread.call(DataflowBatchWorkerHarness.java:120) org.apache.beam.runners.dataflow.worker.DataflowBatchWorkerHarness$WorkerThread.call(DataflowBatchWorkerHarness.java:107) java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) java.base/java.lang.Thread.run(Thread.java:834) Caused by: java.lang.UnsatisfiedLinkError: /tmp/DeviceDetectionHashEngine-linux-x64.so13794783279863211898: libatomic.so.1: cannot open shared object file: No such file or directory java.base/java.lang.ClassLoader$NativeLibrary.load0(Native Method) java.base/java.lang.ClassLoader$NativeLibrary.load(ClassLoader.java:2430) java.base/java.lang.ClassLoader$NativeLibrary.loadLibrary(ClassLoader.java:2487) java.base/java.lang.ClassLoader.loadLibrary0(ClassLoader.java:2684) java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2617) java.base/java.lang.Runtime.load0(Runtime.java:767) java.base/java.lang.System.load(System.java:1831) fiftyone.pipeline.engines.fiftyone.flowelements.interop.LibLoader.load(LibLoader.java:136) fiftyone.devicedetection.hash.engine.onpremise.interop.swig.DeviceDetectionHashEngineModuleJNI.<clinit>(DeviceDetectionHashEngineModuleJNI.java:275) fiftyone.devicedetection.hash.engine.onpremise.interop.swig.ConfigHashSwig.<init>(ConfigHashSwig.java:40) fiftyone.devicedetection.hash.engine.onpremise.flowelements.DeviceDetectionHashEngineBuilder.<init>(DeviceDetectionHashEngineBuilder.java:64) ... 42 more`

Please note that, we are bundling all jars (including 51Degrees jars) as a single runnable jar. 
We see the following so files
- DeviceDetectionHashEngine-linux-aarch64.so
- DeviceDetectionHashEngine-linux-armhf.so
- DeviceDetectionHashEngine-linux-x64.so
- DeviceDetectionHashEngine-linux-x86.so

How can we move forward on the above issue? 
Please note that we can't use API as we need to run the device detection for more than a 10M records per day.

**Comment by jwrosewell** [comment]
We've had an initial look and see two areas to look into.

1. The inner exception includes the following information.

   `/tmp/DeviceDetectionHashEngine-linux-x64.so13794783279863211898: libatomic.so.1: cannot open shared object file:`
    
   It is possible that Libatomic is not available in the environment. If not then it will need to be added.

2. We do not test bundling the jars so don't know what the consequences of doing so would be. If Libatomic is available then investigating the paths that are used when the native library is loaded will be the next step. See this [line](https://github.com/51Degrees/pipeline-java/blob/93994b6bec7a1f71da36a84c86c1775532e82e10/pipeline.engines.fiftyone/src/main/java/fiftyone/pipeline/engines/fiftyone/flowelements/interop/LibLoader.java#L136) of code.

**Comment by samuel-flix** [comment]
@jwrosewell 
Is libatomic.so.1 part of the 51Degrees jar? or do we need to add it manually?

**Comment by jwrosewell** [comment]
It's part of Linux. Here's a [link](https://51degrees.com/documentation/4.4/_info__f_a_qs.html#Dependencies_Glibc_Libatomic) to the FAQ on the subject.

**Comment by samuel-flix** [comment]
We are trying to install the required package in the Google cloud dataflow worker nodes. Since these nodes are dynamic, it is not easy to install packages in them.  Will update here accordingly.

In the meantime, Is there any other possibility without the system libraries?
Previously we used .dat version of the data file instead of Trie. Do you have the option to use .dat file in version 4 as well?

Below is the code we used in version 3
```
        LOG.info("Loading data file");
        String fiftyoneDataFile = resourceToFile("/51Degrees.dat", "51Degrees.dat");
        LOG.info("Loaded data file");
        try {
            return new fiftyone.mobile.detection.Provider(MemoryFactory.create(fiftyoneDataFile));
        } catch (IOException e) {
            throw new FMException(e);
        }

```

**Comment by jwrosewell** [comment]
You could compile the native code to exclude mutli-threaded operations and handle this yourself in the calling code.  See the [section on single threaded](https://github.com/51Degrees/common-cxx#nothreading) operation. 

FYI The [threading.h](https://github.com/51Degrees/common-cxx/blob/73065349dc2b49c36f6e073562a4969bb2629cea/threading.h)/[c](https://github.com/51Degrees/common-cxx/blob/73065349dc2b49c36f6e073562a4969bb2629cea/threading.c) files contain the code that uses libatomic on Linux.

The on premise V4 solution is designed to provide the very fastest performance in C code. It's used in NGINX, Varnish, HAProxy and other high performance network devices. As such it uses modern interlocked CPU operations for parallel processing. These require Libatomic. 

The V3 data files (.dat & .trie) are not as efficient as the V4 ones and do not support [User Agent Client Hints](http://51degrees.com/resources/blogs/tag/Client%20Hints).

**Comment by samuel-flix** [comment]
@jwrosewell - thanks for your support. Able to run this in Cloud Dataflow worker nodes, by creating a customized docker images
