### ISSUE TITLE
Maven and GitHub version discrepancy 

### ISSUE THREAD

**Issue by kirstin51D** [51Degrees/device-detection-java#44]
Currently, the latest version in the Maven Central Repository is version 4.4.42, whereas the provided GitHub repository was at version 4.4.21-SNAPSHOT.
This is due to a problem with the CI which had not been noticed. It doesn’t mean that the package is invalid, but it does mean that we’re not correctly setting the version in GitHub. We plan to address this soon.

**Comment by justadreamer** [comment]
We checked that this is not the case - maven version == github version for all java packages. So this can be closed.
