### ISSUE TITLE
Problems with example documentation pages

### ISSUE THREAD

**Issue by Steve51D** [51Degrees/device-detection-java#6]
Copied from internal issues system:

https://51degrees.com/documentation/4.1/_examples__device_detection__automatic_updates__update_on_startup__on_premise_hash.html

Looking at Java, the first link doesn't take you anywhere and the GitHub link is broken. Needs to be checked for other languages as well.

We also state twice that the example requires a free and paid for data file. Should we not remove the wording for free as you cant set up auto updates by pulling the file from GitHub?

Style wise, the two final paragraphs on node are flipped in comparison to java and .net.

**Comment by fatima51Degrees** [comment]
Fixed the broken GItHub URLs.
