### ISSUE TITLE
Set hour, minute and second when returning dates

### ISSUE THREAD

**Issue by jwrosewell** [51Degrees/device-detection-java#8]
The follow code returns the day, month and year that the date file was published or that the next file will be available but does not set the hour, minute and seconds resulting in different values every time the method is called for some implementations.

https://github.com/51Degrees/device-detection-java/blob/673bfa1e91b733c7041eb6f73952258a40f4aca3/device-detection.hash.engine.on-premise/src/main/java/fiftyone/devicedetection/hash/engine/onpremise/flowelements/DeviceDetectionHashEngine.java#L218

Set the hour, minute and second should be set explicitly to mirror the C# implementation.

https://github.com/51Degrees/device-detection-dotnet/blob/9b0522e70ec9c048ea4e50670c2a335320a69a64/FiftyOne.DeviceDetection/FiftyOne.DeviceDetection.Hash.Engine.OnPremise/FlowElements/DeviceDetectionHashEngine.cs#L447

**Comment by Steve51D** [comment]
This issue has been resolved with the release of version 4.3.3
